name: Copyright

# IMPORTANT: A schedule workflow action *must* be placed on the default branch
# of the repository. Only then will it run as scheduled. It is also placed in a
# queue when scheduled, so it may not run exactly at the requested time.
on:
  # Calculated using crontab.guru. See here: https://crontab.guru/#1_0_1_1_*.
  # Scheduled to run at 00:01 on January 1st of each year.
  schedule:
    - cron: "1 0 1 1 *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-copyright-notice:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Update copyright notice
        run: ./scripts/update_copyright_licence_header.sh

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          branch: automation/update-copyright-notices
          commit-message: "Automated update of copyright notices."
          title: "Automated update of copyright notices"
          body: "This PR was generated by a scheduled/manual GitHub Actions run."
